# Generated by Django 4.1 on 2022-09-22 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetmgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assetmgt.users', verbose_name='User'),
        ),
    ]
