# Generated by Django 4.1 on 2022-09-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetmgt', '0003_alter_assetmodel_date_allotted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='accessory_type',
            field=models.CharField(max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetmgt.assetmodel', verbose_name='Of Asset'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='model_id',
            field=models.CharField(max_length=30, verbose_name='Model ID'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='brand_name',
            field=models.CharField(max_length=15, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='date_allotted',
            field=models.DateField(default=None, null=True, verbose_name='Date Allotted'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='date_procured',
            field=models.DateField(verbose_name='Date Procured'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='model_id',
            field=models.CharField(max_length=20, verbose_name='Model ID'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='type_of_asset',
            field=models.CharField(choices=[('CPU', 'Cpu'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Monitor', 'Monitor')], max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assetmgt.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(max_length=10, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
