# Generated by Django 4.1 on 2022-09-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmgt', '0004_alter_accessories_accessory_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='type_of_asset',
            field=models.CharField(choices=[('CPU', 'CPU'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Monitor', 'Monitor')], max_length=30, verbose_name='Type'),
        ),
    ]
